GET http://localhost:3000/api/usuario 

#####

GET http://localhost:3000/api/usuario/tg56-trg4-t4hg-3rde-uj6t


####

POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
   "idUsuario": "tg59-trg4-t4hg-3rde-uj4t",
    "nombre": "ramiro",
    "apellido": "garcia",
    "email": "ramirogarcia@gmail.com",
    "nroTelefono":111,
    "contraseniaUser": "111",
    "mascotas": ["gato","perra"]
}

####
PUT http://localhost:3000/api/usuario/tg56-trg4-t4hg-3rde-uj6t
Content-Type: application/json

{
    "nombre": "sofia",
    "apellido": "coppari",
    "email": "sofiacoppari@gmail.com",
    "nroTelefono":200,
    "contraseniaUser": "000",
    "mascotas": ["huron","conejo"]
}

####


PATCH http://localhost:3000/api/usuario/tg56-trg4-t4hg-3rde-uj6t
Content-Type: application/json

{
    
    "email": "mailnuevoo@gmail.com",
    "nroTelefono":554
}

####

DELETE http://localhost:3000/api/usuario/tg56-trg4-t4hg-3rde-uj6t
