//Obtener todos los veterinarias
GET http://localhost:3000/api/veterinaria

##Obtener un veterinaria por id
GET http://localhost:3000/api/veterinaria/tg56-trg4-t4hg-3rde-papa

##Crear un veterinaria
POST http://localhost:3000/api/veterinaria/
Content-Type: application/json

{
   "idveterinaria": "tg59-trg4-t4hg-3rde-papa",
   "contraseniaVet": "12345",
    "nombreVet": "Vet24",
    "direccion": "Piagio 123",
    "nroTelefono":3414579233,
    "email": "vet24@gmail.com",
    
}

##modificar un veterinaria (PUT - recurso completo)
PUT http://localhost:3000/api/veterinaria/tg56-trg4-t4hg-3rde-papa
Content-Type: application/json

{
   "idveterinaria": "tg59-trg4-t4hg-3rde-mama",
   "contraseniaVet": "12345",
    "nombreVet": "Veter",
    "direccion": "Oroño 456",
    "nroTelefono":3414379430,
    "email": "veter@gmail.com",
}

##modificar un veterinaria (PATCH - recurso parcial)
PATCH http://localhost:3000/api/veterinaria/tg59-trg4-t4hg-3rde-mama
Content-Type: application/json

{
    "email": "mailnuevo@gmail.com",
    "nroTelefono":554
}

##Borrar un veterinaria
DELETE http://localhost:3000/api/veterinaria/tg33-trg4-t4hg-3rde-uj1t 
//ESE CODIGO NO DIRIGE A NINGUNA VETERINARIA