GET http://localhost:3000/api/veterinaria

#####

GET http://localhost:3000/api/veterinaria/tg56-trg4-t4hg-3rde-papa


####

POST http://localhost:3000/api/veterinaria/
Content-Type: application/json

{
   //"idVeterinaria": "tg59-trg4-t4hg-3rde-bro",
   "contraseniaVet": "12345",
    "nombreVet": "Vet24",
    "direccion": "Piagio 123",
    "nroTelefono":3414579233,
    "email": "vet24@gmail.com"
}

####
PUT http://localhost:3000/api/veterinaria/tg56-trg4-t4hg-3rde-papa
Content-Type: application/json

{
    //"idVeterinaria": "tg59-trg4-t4hg-3rde-mama",
    "contraseniaVet": "12345",
    "nombreVet": "Veter",
    "direccion": "Oroño 456",
    "nroTelefono":3414379430,
    "email": "veter@gmail.com"
}

####


PATCH http://localhost:3000/api/veterinaria/tg56-trg4-t4hg-3rde-papa
Content-Type: application/json

{
    "email": "mailnuevo@gmail.com",
    "nroTelefono":554
}

####

DELETE http://localhost:3000/api/veterinaria/tg56-trg4-t4hg-3rde-papa
