### obtener todos los antecedentes
GET http://localhost:3000/api/antecedentes


### obtener un antecedente  ????esta bien esto??
GET http://localhost:3000/api/antecedentes/1
### crear un nuevo antecedente
POST http://localhost:3000/api/antecedentes
Content-Type: application/json

{
  "descripcion": "desc generica de antecedente",
  "fecha": "2024-09-12T10:00:00",
  "nombreMotivo": "nombre motivo generico",
  "id": 1
}

### modificar un antecedente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/antecedentes/1
Content-Type: application/json

{
  "descripcion": "desc generica de antecedente2",
  "fecha": "2024-09-13T10:00:00",
  "nombreMotivo": "nombre motivo generico2"
}

### modificar un antecedente (PATCH - recurso parcial)
PATCH http://localhost:3000/api/antecedentes/1
Content-Type: application/json

{
  "nombreMotivo": "nombre motivo generico4",
  "descripcion": "otra cosa"
}
### borrar un antecedente
DELETE http://localhost:3000/api/antecedentes/1